### PR TITLE
add json2.js to support ie67

### PR DESCRIPTION
**Pull request by fool2fish**
1. download [douglas's json2.js](https://github.com/douglascrockford/JSON-js/blob/master/json2.js) and save at queen/static
2. modify queen/static/index.html to add json2.js script link 
3. by the way, i use eclipse, so, add '.project' to .gitignore

maybe you don't need to concern with ie67, but many other person, like me, need to take care about them, i indeed hope you can accept this request

### CODE REVIEW

**Comment by unsetbit** [comment]
IE 6 and 7 are already supported, are you running to issues with it?

The json3 polyfill is bundled in to the distributable file during build time. It's at the very top of this file: https://github.com/turn/queen/blob/stable/static/queen.js

**Comment by unsetbit** [comment]
Also, you can add local ignore rules to your .git/info/exclude file. That way we can keep the .gitignore clear of rules unrelated to the project.

**Comment by fool2fish** [comment]
i'll deal with my .git/info/exclude file

but are you sure queen is ok in ie67 ?  my teammate  and i both met this problem

wait a minite, i'll show you a screenshot

**Comment by fool2fish** [comment]
46600297a0e55a045b88930c7fc1ca01

i just run `queen -c 0.0.0.:9000` and then visite {{myip}}:9000 in ie6

and it is the same in ie7

**Comment by unsetbit** [comment]
Hmm. weird. I'll have another look at it, but I have been running it successfully on IE6 fine.

Is the source code of the capture page modified at all? Currently the JSON package is scoped only within the client-side Queen application (if you refer to it outside of the WorkerProvider file, it'll be undefined).

**Comment by fool2fish** [comment]
To make sure of that, I ran queen not only installed by npm but also from the source code(no modification), they both got the same result.

I followed your [thrill's quick start](https://github.com/turn/thrill/wiki/Use), step 1 to step 4.

The only difference is: I use a ie6 of another computer to visit {{myip}}:9000. Dose this has some concern with that problem?

**Comment by unsetbit** [comment]
No it should work, I just don't know why it's not... I'll look in to this this week. I'm going to leave the merge request open for now since json3 _should_ be included already, I think there's something else going on.

**Comment by unsetbit** [comment]
Just a check-in. I've not forgotten about this. We're experiencing a similar problem (there's even more motivation for me to look in to this).

**Comment by unsetbit** [comment]
Ok, I finally figured out the problem. The JSON3 polyfill was getting confused and thinking that it was not in a browser environment, so it never tried to attach itself to the global scope. I committed a fix that ensures that if the JSON property doesn't exist in window, the one from JSON3 gets bound to it. This should resolve this issue. Sorry it took so long.

The change is committed to master. I haven't updated the NPM package yet.

**Pull request closed without merging**
